name: AutoCoder Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Generate Code with ChatGPT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          chmod +x scripts/script.sh
          ./scripts/script.sh "$GH_TOKEN" "$REPO" "$ISSUE_NUM" "$OPENAI_KEY"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: Display Generated Code
        run: ls -R autocoder-artifact
